config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="is-preload">
    <!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
					<header id="header">
						<div class="inner">

							<!-- Nav -->
								<nav>
									<ul>
										<li><a href="#menu">Menu</a></li>
									</ul>
								</nav>

						</div>
					</header>

				<!-- Menu -->
					<nav class='navbar-inverse' id="menu">
						<h2>Menu</h2>
						<ul>
							<li><%= link_to 'One', pages_one_path %></li>
							<li><%= link_to 'Two', pages_two_path %></li>
							<li><%= link_to 'Three', pages_three_path %></li>
						</ul>
					</nav>

				<!-- Main -->
          <div id="main">
            <%= yield %>
          </div>

        <!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<ul class="copyright">
								<li>&copy; Untitled. All rights reserved</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>
  </body>

  <%= javascript_include_tag 'application' %>
</html>

app/views/pages/one.html.erb
<h1>Página One</h1>
<h1>Lissette Andrea Urso Goddard</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h2>Página Three</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sollicitudin, dolor id dapibus maximus, risus lectus varius ante, in tincidunt
neque ex ac elit. Nulla semper vel arcu eget varius. In hac habitasse platea dictumst. Suspendisse ac vehicula nisi. Etiam eget elit sem.
Integer luctus finibus semper. Vestibulum est nunc, pharetra ut tellus vel, aliquet condimentum velit. Duis sed urna mi. Morbi convallis ex
sed tortor euismod vestibulum. Integer dui enim, posuere sit amet suscipit in, imperdiet non justo. Aenean felis tortor, sollicitudin eu
blandit at, dictum sit amet sapien.</p>

app/views/pages/two.html.erb
<h1>Pages#two</h1>
<p>Find me in app/views/pages/two.html.erb</p>
<%= image_tag 'Screenshot.png'%>